FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install
RUN npm install -g nodemon

# Copy the rest of the application code to the container
COPY . .

# Expose the port on which your Node.js application will run
EXPOSE 3002

# Command to run your Node.js application
CMD ["npm", "start"]

